//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IOTDTC_DESPACHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IOTDTC_DESPACHO()
        {
            this.IOTDTM_DOC_EXTERNO = new HashSet<IOTDTM_DOC_EXTERNO>();
        }
    
        public short SIDEMIEXT { get; set; }
        public string VNUMREGSTD { get; set; }
        public string VANIOREGSTD { get; set; }
        public string CTIPDOCIDEREM { get; set; }
        public string VNUMDOCIDEREM { get; set; }
        public string VCODUNIORGREM { get; set; }
        public string VUNIORGREM { get; set; }
        public string VCUO { get; set; }
        public string VRUCENTREC { get; set; }
        public string VNOMENTREC { get; set; }
        public string VNUMREGSTDREC { get; set; }
        public string VANIOREGSTDREC { get; set; }
        public string VUNIORGSTDREC { get; set; }
        public string VDESANXSTDREC { get; set; }
        public Nullable<System.DateTime> DFECREGSTDREC { get; set; }
        public string VUSUREGSTDREC { get; set; }
        public byte[] BCARSTDREC { get; set; }
        public string VOBS { get; set; }
        public string VCUOREF { get; set; }
        public string CFLGEST { get; set; }
        public Nullable<System.DateTime> DFECENV { get; set; }
        public string VUSUREG { get; set; }
        public System.DateTime DFECREG { get; set; }
        public string VUSUMOD { get; set; }
        public Nullable<System.DateTime> DFECMOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IOTDTM_DOC_EXTERNO> IOTDTM_DOC_EXTERNO { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IOTDTC_RECEPCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IOTDTC_RECEPCION()
        {
            this.IOTDTM_DOC_EXTERNO = new HashSet<IOTDTM_DOC_EXTERNO>();
        }
    
        public short SIDRECEXT { get; set; }
        public string VRUCENTREM { get; set; }
        public string VUNIORGREM { get; set; }
        public string CTIPDOCIDEREM { get; set; }
        public string VNUMDOCIDEREM { get; set; }
        public string VNUMREGSTD { get; set; }
        public string VANIOREGSTD { get; set; }
        public string VUNIORGSTD { get; set; }
        public string CCODUNIORGSTD { get; set; }
        public string VDESANXSTD { get; set; }
        public Nullable<System.DateTime> DFECREGSTD { get; set; }
        public string VUSUREGSTD { get; set; }
        public byte[] BCARSTD { get; set; }
        public string VCUO { get; set; }
        public string VCUOREF { get; set; }
        public string VOBS { get; set; }
        public string CFLGESTOBS { get; set; }
        public string CFLGEST { get; set; }
        public System.DateTime DFECREG { get; set; }
        public string VUSUMOD { get; set; }
        public Nullable<System.DateTime> DFECMOD { get; set; }
        public string CFLGENVCAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IOTDTM_DOC_EXTERNO> IOTDTM_DOC_EXTERNO { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IOTDTD_ANEXO
    {
        public short SIDDOCANX { get; set; }
        public string VNOMDOC { get; set; }
        public short SIDDOCEXT { get; set; }
        public System.DateTime DFECREG { get; set; }
    
        public virtual IOTDTM_DOC_EXTERNO IOTDTM_DOC_EXTERNO { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IOTDTD_DOC_PRINCIPAL
    {
        public short SIDDOCPRI { get; set; }
        public short SIDDOCEXT { get; set; }
        public string VNOMDOC { get; set; }
        public byte[] BPDFDOC { get; set; }
        public string CCODEST { get; set; }
        public System.DateTime DFECREG { get; set; }
    
        public virtual IOTDTM_DOC_EXTERNO IOTDTM_DOC_EXTERNO { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IOTDTM_DOC_EXTERNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IOTDTM_DOC_EXTERNO()
        {
            this.IOTDTD_ANEXO = new HashSet<IOTDTD_ANEXO>();
            this.IOTDTD_DOC_PRINCIPAL = new HashSet<IOTDTD_DOC_PRINCIPAL>();
        }
    
        public short SIDDOCEXT { get; set; }
        public string VNOMENTEMI { get; set; }
        public string CCODTIPDOC { get; set; }
        public string VNUMDOC { get; set; }
        public System.DateTime DFECDOC { get; set; }
        public string VUNIORGDST { get; set; }
        public string VNOMDST { get; set; }
        public string VNOMCARDST { get; set; }
        public string VASU { get; set; }
        public string CINDTUP { get; set; }
        public Nullable<short> SNUMANX { get; set; }
        public short SNUMFOL { get; set; }
        public string VURLDOCANX { get; set; }
        public Nullable<short> SIDEMIEXT { get; set; }
        public Nullable<short> SIDRECEXT { get; set; }
    
        public virtual IOTDTC_DESPACHO IOTDTC_DESPACHO { get; set; }
        public virtual IOTDTC_RECEPCION IOTDTC_RECEPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IOTDTD_ANEXO> IOTDTD_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IOTDTD_DOC_PRINCIPAL> IOTDTD_DOC_PRINCIPAL { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOCUMENTO
    {
        public string CIDTIPDOC { get; set; }
        public string VDESTIPDOC { get; set; }
        public string CCODTIPODOC { get; set; }
    }
}
